routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('/welcome');
});

Auth::routes();

//###################para catalogo############################
Route::get("/catalogo","catalogoController@index");
Route::post('/catalogo','catalogoController@search_for_catalogo')->name('buscar_catalogo');
Route::post('/busqueda','catalogoController@buscar_opciones')->name('buscar_opciones');
Route::post("/buscar_articulo","catalogoController@buscar_articulo");


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth', 'verified'])->group(function () {

    //para creditos
    Route::post("/credito","creditosController@completar_credito");    

    //ir a view cajas
    Route::get("/cajas","generalController@administrar_cajas");
    Route::post("/registrar_caja","generalController@registrar_caja");
    Route::post("/actualizar_caja","generalController@actualizar_caja");
    Route::post("/eliminar_caja","generalController@eliminar_caja");


  //registrar usuarios
    Route::get("/list-user","generalController@listar_usuarios");
    Route::get("/registrar", "generalController@registrar"); //para mostrar la vista de regsitrar
    // Route::post("register", "Auth\RegisterController@register")->name("register"); //ejecutar form
    Route::post("register", "generalController@registrar_user")->name("register"); //ejecutar form
    Route::post("/actualizar_user","generalController@actualizar_user");
    Route::get("/eliminar_user/{id}","generalController@eliminar_user");

    //para salidas
    Route::post("/storesalida", "generalController@storesalidas");
    Route::post("/buscarsalidas", "generalController@buscarsalidas");
    Route::post("/eliminarsalida", "generalController@eliminarsalida");
    Route::post("/editar_salida", "generalController@editar_salida");
    //para turnos
    Route::post("/storeturno", "generalController@storeturno");
    Route::post("/cerrarturno", "generalController@cerrarturno");

  
    //para venta
    Route::get("/ventas", "ventasController@index");
    Route::post("/ejecutar_venta", "ventasController@ejecutar_venta");
    Route::post("/cotizacion", "ventasController@cotizacion");
    Route::post("/buscar_venta", "ventasController@buscar_venta"); //buscar ventas por id
    Route::post("/devolucion", "ventasController@devolucion");
    Route::post("/last_venta","ventasController@data_last_venta");
    Route::post("/reimprimir","ventasController@reimprimir");

    //para articulos##############
    Route::get("/articulos", "articulosController@index");
    Route::get("/buscar_articulos","articulosController@buscar_articulos");
    Route::get("/registrar_articulo","articulosController@registrar_articulo");
    Route::get("/editar_articulo/{id}","articulosController@edit");
    Route::post("/update_articulo/{id}","articulosController@update");
    Route::get("/listar_articulos","articulosController@listar_articulos");
    
    Route::post("articulo", "articulosController@store")->name('store_articulo');
    Route::get("buscarArticulo", "articulosController@buscarArticulos")->name('buscarArtiulos');
    Route::post("/buscar_x_codigo", "articulosController@buscar_x_codigo");

    Route::post("buscarExistencia", "articulosController@buscarExistencia")->name('buscarExistencia');
    Route::post("updateExistenca", "articulosController@updateExistenca")->name('updateExistenca');
    Route::post("eliminarArticulo", "articulosController@eliminarArticulo")->name("eliminarArticulo");

    Route::post("marcas", "articulosController@store_marca")->name("store_marca");
    Route::post("provedor", "articulosController@store_provedor")->name("store_provedor");

    Route::post('/uploadImg','articulosController@uploadImg');

    Route::get('/storeCategoria','articulosController@createCategoria')->name('storeCategoria');
    Route::get('/storeLinea','articulosController@createLinea')->name('storeLinea');
    Route::get('/storeMarca','articulosController@createMarca')->name('storeMarca');


    //################clientes##############
    Route::get("/clientes", "clientesController@index");
    Route::post("cliente", "clientesController@store")->name("storeCliente");
    Route::get("/edit_clientes/{id}","clientesController@edit_clientes");
    Route::post("/actualizar-cliente","clientesController@actualizar");
    Route::post("destroycliente", "clientesController@destroy")->name("destroyCliente");
    Route::post("showCliente", "clientesController@showCliente")->name("showCliente");
    Route::post("/updateCliente", "clientesController@update");
    Route::post('/uploadimgCliente','clientesController@uploadimgCliente');
    //-------------------------------RUTAS-----------------------------------------------------
    Route::get("/rutas","clientesController@rutas");
    Route::post("/guardar_ruta","clientesController@guardar_ruta")->name('guardar_ruta');
    Route::post("/actualizar_ruta","clientesController@actualizar_ruta")->name('actualizar_ruta');
    Route::post("/see_ruta","clientesController@see_ruta")->name('see_ruta');
    Route::post("/edit_ruta","clientesController@edit_ruta")->name('edit_ruta');
    Route::post("/destroy_ruta","clientesController@destroy_ruta")->name('destroy_ruta');
    

    //------------------para pedidos--------------------------
    Route::get('/pedidos', 'pedidosController@index')->name('pedidos');
    Route::get("/nuevo_pedido","pedidosController@nuevo_pedido");
    Route::post("/buscar_cliente","pedidosController@buscar_clientes");
    Route::post("/buscar_clientes_x_id","pedidosController@buscar_clientes_x_id");
    Route::post("/generando_pedido","pedidosController@generando_pedido");
    Route::post("/eliminar_pedido","pedidosController@destroy");
    Route::post("/editar_info_pedido","pedidosController@editar_info_pedido");
    Route::post("/change_status","pedidosController@change_status");
    Route::get("/retomar/{id}","pedidosController@retomar");
    Route::post("/guardar_cambios_pedido","pedidosController@guardar_cambios_pedido");
    Route::get("/imprimir_ticket/{id}","pedidosController@imprimir");

    Route::get('/verPedido/{id}', 'pedidosController@verPedido')->name('verPedido');
    Route::get('/paraPedidos', 'ventasController@paraPedidos')->name('paraPedidos');
    Route::post('/crearpedido', 'pedidosController@crearpedido')->name('crearpedido');
    Route::post("actualizar-pedido",'pedidosController@actualizar')->name('actualizar-pedido');
    Route::post("/verProdutosPedido",'pedidosController@verProPedido')->name("verProdutosPedido");
    
    

    
    //buscar cliente para nuevo pedido--------------------------
    Route::post("/buscarClientes",'clientesController@buscarClientes')->name("buscarClientes");





    //####################para informes############################
    Route::get("/movimientos", "informesController@movimientos");
    Route::get("/salidas", "informesController@salidas");
    Route::get("/turnos", "informesController@turnos");
    Route::get("/lista_venta", "informesController@ventas");
    //####################para marcas########################
    Route::post("/update_marca", "articulosController@update_marca");
    Route::post("/delete_marca", "articulosController@delete_marca");
    //#####################para provedor#############################
    Route::post("/update_provedor", "articulosController@update_provedor");
    Route::post("/delete_provedor", "articulosController@delete_provedor");
    //////#################informes#############################
    Route::get("/informes","HomeController@get_informes");
    Route::get("/informes_venta","ventasController@informes_ventas");


    //para ofertas#################################
    Route::resource('ofertas','ofertasController');
    Route::post('/crearOferta','ofertasController@createOferta')->name('crearOferta');
    Route::post('/buscarProducto','ofertasController@buscarProducto')->name('buscarProducto');


    //#####################para movimientos#######################

    Route::get("/movimientos","movimientosController@index");
    Route::post("/buscar_info_cliente","movimientosController@buscar_info_cliente");
    Route::get("/load_movimientos/{id}","movimientosController@load_movimientos");
    Route::get("/get_por_cobrar/{id}","movimientosController@get_por_cobrar");

    //#########################para abono###################################
    Route::post("/abono","movimientosController@abono");
    Route::get("movimiento_pdf/{id}/{tipo}","movimientosController@pdf");
    Route::get("/movimiento_excel/{id}/{tipo}","movimientosController@excel");
    Route::post("/liquidar","movimientosController@liquidar");
    //#####################para turnos""########################################
    Route::get("/imprimir_corte_turno/{id}","generalController@imprimir_corte_turno");
    Route::post("/total_venta","ventasController@total_venta_x_turno");

    //###############################BD#############################################
    Route::get("/bd","generalController@bd");
    Route::post("/update_database","generalController@update_database");

    //#############################inventarios#########################
    Route::get("/inventarios","inventariosController@index");
    Route::post("/buscar_en_inventario","inventariosController@buscar_en_inventario");

});



Route::get("/verificador","verificadorController@index")->name("verificador");
Route::post("verificador","verificadorController@buscar")->name("buscar");;

resources/views/forms/bd.blade.php
@extends('layouts.app')
@section('content')

<div class="container-fluid">
	<div class="card">
		<div class="card-header">
			<p>ACTUALIZAR LA TABLA ARTICULOS DESDE LOS DATOS DEL SERVIDOR NALAEXPRESS.COM</p>
		</div>
		<div class="card-body">

			<form method="post" action="{{url('/update_database')}}">
				@csrf
				<button type="submit" class="btn btn-lg btn-primary" id="btn_actualizar">Actualizar Articulos</button>
				<span style="margin-left: 20%;display: none;" id="espere">ESPERE... <i class="fas fa-2x fa-spinner fa-spin"></i></span>
			</form>
			<br><br>
			@if(session("status"))
				<div class="alert @if(session('status')=='success') alert-success @else alert-error @endif" id="alert">
				@if(session('status')=='success')
				<b>Actualizado correctamente.</b>
				@else
				<b>ERROR al intentar actualiza, verifique si hay conexión con el servidor, es posible que no tenga conexión a internet</b>
				@endif
			</div>
			@endif

		</div>
	</div>
</div>
@endsection
@section('script')
<script type="text/javascript">

	$("#btn_actualizar").click(function(){
		$("#espere").show();
	});

	
	@if(session("status"))
		setInterval(function(){
			$("#alert").hide();
		},60000);
	@endif
	
</script>
@endsection

resources/views/forms/list_ventas.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
	<label>INFORMES DE VENTAS</label>
</div>



<div class="card">
	<div class="card-body">
		<h2 class="text-center text-primary"> <i class="fas fa-shopping-basket "></i> VENTAS</h2>
		

		<div class="table-responsive">
			<table class="table table-striped table-bordered text-center" id="table_ventas">
				<thead class="bg-primary text-white">
					<tr>
						<th>#</th>
						<th>usuario</th>
						<th>turno</th>
						<th>Caja</th>
						<th>total</th>
						<th>realizado</th>
						<th><i class="fas fa-cog"></i></th>
					</tr>
				</thead>
				<tbody >
					@foreach($ventas as $venta)
					@if(Auth::user()->caja!=null)
						@if(Auth::user()->caja==$venta->caja && Auth::user()->name==$venta->usuario)
							<tr>
								<td>{{ str_pad($venta->id, 8, '0', STR_PAD_LEFT)}}</td>
								<td>{{$venta->usuario}}</td>
								<td>T{{ str_pad($venta->id_turno, 6, '0', STR_PAD_LEFT)}}</td>
								<td>{{$venta->caja}}</td>
								<td class="text-right"><b>${{$venta->total_venta}}</b> </td>
								<td>{{$venta->created_at}}</td>
								<td>
									<button class="btn btn-sm btn-success" onclick="verarticulos({{$venta->id}});"><i class="fas fa-eye"></i></button>
										<button  class="btn btn-sm btn-secondary" onclick="reimprimir({{$venta->id}});"><i class="fas fa-print"></i></button>	
								</td>
							</tr>
							@endif
					@else
						<tr>
								<td>{{ str_pad($venta->id, 8, '0', STR_PAD_LEFT)}}</td>
								<td>{{$venta->usuario}}</td>
								<td>T{{ str_pad($venta->id_turno, 6, '0', STR_PAD_LEFT)}}</td>
								<td>{{$venta->caja}}</td>
								<td class="text-right"><b>${{$venta->total_venta}}</b> </td>
								<td>{{$venta->created_at}}</td>
								<td>
									<button class="btn btn-sm btn-success" onclick="verarticulos({{$venta->id}});"><i class="fas fa-eye"></i></button>
										<button  class="btn btn-sm btn-secondary" onclick="reimprimir({{$venta->id}});"><i class="fas fa-print"></i></button>	
								</td>
							</tr>
					@endif
					@endforeach
				</tbody>
			</table>
			<div class="float-right">
						{{$ventas->links()}}
				</div>
		</div>
	</div>
</div>



<!--window modal ######modal busqueda################-->
  <div class="modal fullscreen-modal fade" id="modal_ver_articulos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header bg-info" style="padding: 2px">
          <h2 id="id_venta_header" class="text-white"></h2>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        </div>
        <div class="modal-body">
        	<div class="row">
        		<div class="col text-primary"><span id="turno"></span></div>
        		<div class="col text-success"><span id="usuario"></span></div>
        		<div class="col text-danger"> <span id="fecha"></span></div>
        	</div>
        <div class="table-responsive">
        	<table class="table table-striped table-bordered text-center" id="table_articulos">
        		<thead class="bg-primary text-center text-white">
        			<tr>
        				<th>cantidad</th>
        				<th>unidad</th>
        				<th>descripción</th>
        				<th>Tipo precio</th>
        				<th>precio</th>
        				<th>subtotal</th>
        			</tr>
        		</thead>
        		<tbody>

        		</tbody>
        	</table>
        </div>
        <div>
        	<h2 id="total" class="float-right text-primary"></h2>
        </div>
        </div>
      </div>
    </div>
  </div>



<style type="text/css">
	#table_ventas_filter label{float: right;}
	.table tbody tr:hover{
		background:#D0ECE7;
	}
	.table td, .table th{
		padding-left: 0px !important;
		padding-right: 0px !important;
		padding: 3px !important;
		height: 20px;
	}
</style>

@endsection
@section('script')
<script type="text/javascript">



function reimprimir(id){
    $.ajax({
      url:"{{url('/reimprimir')}}",
      type:"post",
      dataType:"json",
      data:{id:id},
      success:function(e){
        if(e==true){
          alert("Se reimprimió correctamente.");
        }
      }
    });
}



function verarticulos(id){
	$("#id_venta_header").html("VENTA: "+  ('00000000' + id).slice(-8));
	$("#table_articulos tbody").html('');
	$.ajax({
		url:"{{url('/buscar_venta')}}",
		type:"post",
		dataType:"json",
		data:{id_venta:id},
		success:function(e){
			$("#turno").html("Turno: T"+ ('000000' + e["venta"].id_turno).slice(-6));
			$("#usuario").html("Atendió: "+e["venta"].usuario);
			$("#fecha").html("Fecha: "+e["fecha"]);
			$("#total").html("Total: $"+e["venta"].total_venta);
			$("#modal_ver_articulos").modal("show");

			for(var x=0;x<e["nombres"].length;x++){
				var cantidad=e['cantidad'][x];
				var precio=e['precio'][x];
				precio=parseFloat(precio);
				precio=precio.toFixed(2);
				var total=parseFloat(cantidad)*parseFloat(precio);
				total=total.toFixed(2);

				$("#table_articulos tbody").append("<tr> <td>"+cantidad+"</td>   <td>"+e['unidad'][x]+"</td>   <td>"+e["nombres"][x]+"</td>  <td>"+e["tipo_precio"][x]+"</td><td>$ "+precio+"</td>  <td>$ "+total+"</td>   </tr>");
			}

		},error:function(){

		}
	});
}









	$("#table_ventas").DataTable({
		"order": [[ 0, 'DESC' ]],
		"bPaginate": false,
		"language": {
        "decimal": "",
        "emptyTable": "No hay información",
        "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
        "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
        "infoFiltered": "(Filtrado de _MAX_ total entradas)",
        "infoPostFix": "",
        "thousands": ",",
        "lengthMenu": "Mostrar _MENU_ Entradas",
        "loadingRecords": "Cargando...",
        "processing": "Procesando...",
        "search": "Buscar:",
        "zeroRecords": "Sin resultados encontrados",
        "paginate": {
            "first": "Primero",
            "last": "Ultimo",
            "next": "Siguiente",
            "previous": "Anterior"
        }}});

	$("#table_ventas_filter input").focus();

</script>
@endsection

resources/views/forms/ofertas.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid" style="padding-top:10px">
	@if(session('success'))
		<div class="alert alert-success alert-dismissible fade show">
			<h3>{{session('success')}}</h3>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			    <span aria-hidden="true">&times;</span>
			</button>
		</div>
	@endif
	@if(session('error'))
		<div class="alert alert-danger alert-dismissible fade show">
			<h3>{{session('error')}}</h3>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			    <span aria-hidden="true">&times;</span>
			</button>
		</div>
	@endif

	<div class="card">
		<div class="card-body">
			<div class="col-3 input-group">
				<input class="form-control " type="text" placeholder="Buscar"
	  		aria-label="Search" id="input_search" autofocus="">
	  		<button class="btn btn-primary" id="btn_buscar_prod"><i class="fa fa-search"></i></button>
			</div>
			<br>

			<div class="row">
  			<div class="col-xl-3 col-md-6 mb-4 ">
  				<form action="{{route('crearOferta')}}" method="post" id="form_oferta">
						@csrf
						<input type="number" name="id_producto" id="id_producto" class="d-none" readonly="true">
						<label>Unidad</label>
						<input type="text" name="unidad" id="unidad" class="form-control" readonly="true">

		  			<label for="descripcion">Descripción del producto</label>
		  			<textarea class="form-control" name="descripcion_producto" id="descripcion" readonly="true"></textarea>
		  			
		  			<label>Precio de venta <b class="text-danger">$</b></label>
		  			<input type="number" name="precio_venta" id="precio_venta" class="form-control" readonly="true">

		  			<label >Precio de Oferta</label>
		  			<input type="number" name="precio_oferta" id="precio_oferta" class="form-control border-info">

		  			<label for="validez">Valido hasta</label>
		  			<input type="date" name="fecha_valido" id="validez" class="form-control border-info" >
		  			
		  			<label>Imagen</label>
		  			<input type="text" name="foto" id="foto" class="form-control" readonly="true">

		  			<label>Url de youtube</label>
		  			<input type="text" name="url" id="url" class="form-control border-info">
		  			<br>
		  			<a class="btn btn-success  text-light" id="btn_agregar" style="float: right;"><i class="fa fa-plus text-warning"></i> Agregar</a>
					</form>
  			</div>



  			<div class="col-xl-3 col-md-6 mb-4 contenedor" style="background:#EAECEE;text-align: center;height: 300px;padding-top: 45px" id="div_foto">
    				<img src="img/articulos/no-images.jpg" class="imagen" style='margin-top:auto;margin-bottom:auto;width:80%'>
    		</div>


    		<div class="col-xl-6 col-md-12 mb-4">
    			<hr>
          <b class="badge badge-info" style="font-size: 130%">En oferta  </b> <span><i class="fa fa-shopping-bag text-success fa-2x"></i><h4 class="text-primary"></h4></span>
          <div class="table-responsive">
					  <table class="table table-striped table-bordered" id="tabla_oferta">
					    <thead class="table-dark">
					    	<tr>
					    		<th class="d-none">id</th>
					    		<th>id producto</th>
					    		<th>unidad</th>
					    		<th>Descripción</th>
					    		<th>Precio</th>
					    		<th>Precio de oferta</th>
					    		<th>fecha valido</th>
					    		<th><i class="fa fa-picture-o text-info"></i></th>
					    		<th><i class="fa fa-cog"></i></th>
					    		
					    	</tr>
					    </thead>
					    <tbody id="lista_ofertas">
					    	@foreach($ofertas as $oferta)
					    		<tr>
					    			<td class="d-none">{{$oferta->id}}</td>
					    			<td>{{$oferta->id_producto}}</td>
					    			<td>{{$oferta->unidad}}</td>
					    			<td>{{$oferta->descripcion_producto}}</td>
					    			<td>{{$oferta->precio_venta}}</td>
					    			<td>{{$oferta->precio_oferta}}</td>
					    			<td>{{$oferta->fecha_valido}}</td>
					    			<td>
					    				@if($oferta->foto!=null || $oferta->foto!="ninguno")
					    					<img src="{{asset('/img/articulos/'.$oferta->foto)}}" width="40px">
					    				@else
												<img src="{{asset('/img/articulos/no-images.jpg')}}" width="40px">
					    				@endif
					    			</td>
					    			<td>
					    				<form action="{{ route('ofertas.destroy',$oferta->id) }}" method="post" class="btnAction">
					              			 @csrf
                 							 @method('DELETE')
					              			<button class="btn btn-sm btn-danger" ><i class="fa fa-trash"></i></button>
					              		</form>
					    			</td>
					    		</tr>
					    	@endforeach
					    </tbody>
					  </table>
					</div>
    		</div>
  		</div><!-- fin row -->
		</div><!-- fin card-body -->
	</div><!-- fin card-->
</div><!-- fin container-fluid -->


<div class="modal" tabindex="-1" id="modal_buscar_prod" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#20c997">
        <h5 class="modal-title">Retail Stehs</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<p class="text-info">Pulse doble click para seleccionar el producto.</p>
      	<div class="table-responsive" style="overflow-y: scroll;height: 400px">
				  <table class="table table-striped" id="tab_modal_buscado">
				    <thead class="table-dark">
				    	<tr>
				    		<th>id</th>
				    		<th>Clave</th>
				    		<th>Unidad</th>
				    		<th>Descripción</th>
				    		<th>Precio</th>
				    		<th>Existencia</th>
				    		<th>Foto</th>
				    	</tr>
				    </thead>
					  <tbody id="lista_buscado">
					  	
					  </tbody>
				  </table>
			</div>
      </div>

    </div>
  </div>
</div>



<style type="text/css">
	.contenedor:hover .imagen {-webkit-transform:scale(1.3);transform:scale(1.3);}
	.contenedor {overflow:hidden;}
	#tabla_oferta thead tr th{
		font-size: 60%;
		padding: 2px;
		border:1px;
	}
	#tabla_oferta tbody tr td{
		font-size: 60%;
		padding: 1px;
		border:1px solid #eee;
		border-bottom: 2px solid #66bb6a;

	}
</style>



@endsection

@section('script')
<script type="text/javascript">

var eliminaroferta=function(id){
	alert("eliminando"+id);
}

//-------------------------------------------------------------------------------
	$("#btn_agregar").click(function(){
		var id_pro=$("#id_producto").val();
		var cont=0;
		$("#lista_ofertas").find("tr td:first-child").each(function(){
			cont++;
			if ($(this).siblings("td").eq(0).html()==id_pro) {
				alert("YA ESTA AGREGADO");
			}else{
				$("#form_oferta").submit();
			}
		    });
		
		if (cont==0) {
			$("#form_oferta").submit();
		}
	});
//##############################################################################
	$("#btn_buscar_prod").click(function () {

		
		// alert($("#input_search").val());
		$("#lista_buscado").html('');
		$.ajax({
          url:'{{route("buscarProducto")}}',
          type:'POST',
          dataType:'json',
          data:{
          		busqueda:$("#input_search").val()
          		}
            }
            ).done(function(e){
              if (e=="") {
               $("#lista_buscado").append("<tr class='text-danger'> <td  colspan='8'><b>No se encontró registro!!</b></td></tr>");
              }else{
              	$("#modal_buscar_prod").modal("show");
                for(var x=0;x<e.length;x++){
                	if (e[x].fotos=='ninguno' || e[x].fotos==null) {
                		$("#lista_buscado").append(
	                	"<tr tabindex='1' class='move'><td width='1px' >"
	                	+e[x].id_p+"</td><td>"
	                	+e[x].clave+"</td><td class=''>"
	                	+e[x].unidad+"</td><td>"
	                	+e[x].descripcion_articulo+"</td><td>"
	                	+e[x].pre_unidad+"</td><td>"
	                	+e[x].existencia+"</td> <td class='d-non'><img src='{{asset('')}}/img/articulos/no-images.jpg' style='margin-top:auto;margin-bottom:auto;width:80%' class='imagen'> <span class='d-none'>no-images.jpg</span></td></tr>"
	                	);
                	}else{
                		fotos=e[x].fotos;
                		fotos=fotos.split(",");
                		$("#lista_buscado").append(
	                	"<tr tabindex='1' class='move'><td width='1px' >"
	                	+e[x].id_p+"</td><td>"
	                	+e[x].clave+"</td><td class=''>"
	                	+e[x].unidad+"</td><td>"
	                	+e[x].descripcion_articulo+"</td><td>"
	                	+e[x].pre_unidad+"</td><td>"
	                	+e[x].existencia+"</td> <td class='d-non'><img src='{{asset('')}}/img/articulos/"+fotos[0]+"' style='margin-top:auto;margin-bottom:auto;width:80%' class='imagen'> <span class='d-none'>"+fotos[0]+"</span></td></tr>"
	                	);
                	}
                
               }//fin for
              }
              
              });//fin done 
	});
//_________________________________________________________________________________________________

	$("#lista_buscado").on("dblclick","tr",function(){
		// alert($(this).find("td").eq(0).html());
		$("#id_producto").val($(this).find("td").eq(0).html());
		$("#unidad").val($(this).find("td").eq(2).html());
		$("#descripcion").val($(this).find("td").eq(3).html());
		$("#precio_venta").val($(this).find("td").eq(4).html());
		
		// alert($(this).find("td").eq(6).find("img").attr("src"));
		let fot=$(this).find("td").eq(6).find("span").html();
		$("#foto").val(fot);
		$("#div_foto").html($(this).find("td").eq(6).html());
		$("#modal_buscar_prod").modal("hide");
	});
//______________________________________________________________________________________________________
</script>
@endsection